name: Проверка списка фамилий студентов

on: [push]

jobs:
  test-bash-script:
    runs-on: ubuntu-latest
    name: Тест скрипта на Ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bash script test
      run: |
        chmod +x add_script.sh
	chmod +x check_script.sh
        ./add_script.sh 1.txt
	./add_script.sh 2.txt
	./add_script.sh 3.txt
	./check_script.sh 1.txt
	./check_script.sh 2.txt
	./check_script.sh 3.txt
	
