on: [push]

jobs:
  test-bash-script:
    runs-on: ubuntu-latest
    name: Тест скрипта на Ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bash script test
      run: |
        chmod +x add_script.sh
        chmod +x check_script.sh
        test1=$(./add_script.sh college_students.txt)
        test2=$(./check_script.sh file1.txt file2.txt file3.txt)
        test4=$(./check_script.sh tmp1.txt tmp2.txt tmp3.txt)
        if [ "$test1" = "yes" ]; then
            echo "OK"
        else
            echo "ERROR 1"
            exit 1
        fi
        if [ "$test2" = "yes" ]; then
            echo "OK"
        else
            echo "ERROR 2"
            exit 1
        fi
        if [ "$test3" = "yes" ]; then
            echo "OK"
        else
            echo "ERROR 3"
            exit 1
        fi
        if [ "$test4" = "yes" ]; then
            echo "OK"
        else
            echo "ERROR 4"
            exit 1
        fi
