name: Проверка количества людей в группах

on: [push]

jobs:
  test-bash-script:
    runs-on: ubuntu-latest
    name: Тест скрипта на Ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Проверка работоспособности скрипта №1
      run: |
        chmod +x check_script1.sh
        ./check_script1.sh 1.txt 2.txt
