name: Проверка количества людей в группах

on: [push]

jobs:
  test-bash-script:
    runs-on: ubuntu-latest
    name: Тест скрипта на Ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Проверка работоспособности скрипта №1
      run: |
        chmod +x check_script1.sh
        ./check_script1.sh 1.txt 2.txt
    - name: Проверка работоспособности скрипта №2
      run: |
        chmod +x identical_students.sh
        ./identical_students.sh college_students.txt
    - name: Проверка равного количества студентов в файлах
      run: |
        chmod +x equal_amount.sh
        chmod +x group_comparison.sh
        ./equal_amount.sh
        ./group_comparison.sh group1.txt group2.txt
    - name: Проверка отсутствия одного txt файла
      run: |
        chmod +x transmission_error.sh
        chmod +x group_comparison.sh
        ./transmission_error.sh
        ./group_comparison.sh group1.txt
